Web/Models/FilterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Models
{
    public class FilterViewModel
    {
        [DisplayName("Client")]
        public string ClientId { get; set; }

        [DisplayName("Project")]
        public string ProjectId { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Start date")]
        public DateTime StartDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("End date")]
        public DateTime EndDate { get; set; }
    }
}

Web/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Model;
using Model.Entities;
using Web.Models;

namespace Web.Controllers
{
    public class ActivityController : BaseController<Activity>
    {
        private IEnumerable<TimeLineViewModel> _timeLineList
        {
            get
            {
                //Due to an EF core 2.0 issue, I have to split the query because I can't run GroupBy and Select
                var groupedData = _context.Activities.OrderByDescending(t => t.Date).Include(a => a.Project).Include(a => a.Project.Client).Take(5).GroupBy(t => t.Date).AsEnumerable();
                return groupedData.Select(t => new TimeLineViewModel() { Date = t.Key, Activities = t });
            }
        }

        public ActivityController(TrackingContext context) : base(context)
        {
        }

        // GET: Activity
        public async Task<IActionResult> Index()
        {
            ViewBag.Projects = _projectsList;
            return View(_timeLineList);
        }

        // POST: Activity/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Date,StartTime,EndTime,ProjectId,Id,Name")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                _context.Add(activity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Projects = _projectsList;
            return View(nameof(Index), _timeLineList);
        }

        // GET: Activity/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return NotFound();
            }

            var activity = _context.Activities.SingleOrDefault(m => m.Id == id);
            if (activity == null)
            {
                return NotFound();
            }

            ViewBag.Projects = _projectsList;
            return View(activity);
        }

        // POST: Activity/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Date,StartTime,EndTime,ProjectId,Id,Name")] Activity activity)
        {
            if (id != activity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(activity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Exists(activity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Projects = _projectsList;
            return View(activity);
        }

        // GET: Activity/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return NotFound();
            }

            var activity = _context.Activities.Include(a => a.Project).SingleOrDefault(m => m.Id == id);
            if (activity == null)
            {
                return NotFound();
            }

            return View(activity);
        }

        // POST: Activity/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var activity = _context.Activities.SingleOrDefault(m => m.Id == id);
            _context.Activities.Remove(activity);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Model;
using Model.Entities;

namespace Web.Controllers
{
    public class ClientController : BaseController<Client>
    {
        public ClientController(TrackingContext context) : base(context)
        {
        }

        // GET: Client
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clients.ToListAsync());
        }

        // POST: Client/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nameof(Index), await _context.Clients.ToListAsync());
        }

        // GET: Client/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return NotFound();
            }

            var client = await _context.Clients.SingleOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Client/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Exists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Client/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return NotFound();
            }

            var client = await _context.Clients.SingleOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Client/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var client = await _context.Clients.SingleOrDefaultAsync(m => m.Id == id);
            _context.Clients.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Model;
using Model.Entities;

namespace Web.Controllers
{
    public class ProjectController : BaseController<Project>
    {
        public ProjectController(TrackingContext context) : base(context)
        {
        }

        // GET: Project
        public async Task<IActionResult> Index()
        {
            ViewBag.Clients = _clientsList;
            return View(await _context.Projects.Include(p => p.Client).Include(t=>t.Activities).ToListAsync());
        }
        
        // GET: Project/Create
        public IActionResult Create()
        {
            ViewBag.Clients = _clientsList;
            return View();
        }

        // POST: Project/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientId,Id,Name")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Clients = _clientsList;
            return View(nameof(Index), await _context.Projects.Include(p => p.Client).ToListAsync());
        }

        // GET: Project/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.SingleOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["Clients"] = _clientsList;
            return View(project);
        }

        // POST: Project/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ClientId,Id,Name")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Exists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Clients = _clientsList;
            return View(project);
        }

        // GET: Project/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(p => p.Client)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var project = await _context.Projects.SingleOrDefaultAsync(m => m.Id == id);
            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Model;
using Model.Entities;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Web.Models;
using Newtonsoft.Json;

namespace Web.Controllers
{
    public class ReportController : BaseController<BaseEntity>
    {
        public ReportController(TrackingContext context) : base(context) {}       

        public IActionResult Index() => View();

        public IActionResult Error() => base.View(new ErrorViewModel { RequestId = System.Diagnostics.Activity.Current?.Id ?? HttpContext.TraceIdentifier });

        public async Task<IQueryable<ReportViewModel>> GetReportDataAsync() => _context.Activities
            .Include(t => t.Project)
            .Include(t => t.Project.Client)
            .Select(a => new ReportViewModel
            {
                Client = a.Project != null && a.Project.Client != null ? a.Project.Client.Name : EmptyEntity,
                Project = a.Project != null ? a.Project.Name : EmptyEntity,
                Activity = a.Name,
                Date = a.Date,
                Duration = a.Duration.TotalHours
            });

        public async Task<IActionResult> ReportRead([DataSourceRequest] DataSourceRequest request)
        {
            var reportData = await GetReportDataAsync();
            return Json(await reportData.ToDataSourceResultAsync(request));
        }
    }
}

Web/Views/Shared/Filter.cshtml
@model FilterViewModel
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            @*<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Brand</a>*@
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        @*<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">*@
            <ul class="nav navbar-nav">

            </ul>
            <form class="navbar-form" asp-action="Filter">
               
                <div class="form-group">
                    <label class="control-label" asp-for="ClientId"></label>
                    <select class="form-control filterable" asp-for="ClientId" asp-items="ViewBag.Clients">
                        <option selected>All</option>
                        <option>None Client</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label" asp-for="ProjectId"></label>
                    <select class="form-control filterable" asp-for="ProjectId" asp-items="ViewBag.Projects">
                        <option selected>All</option>
                        <option>None Project</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label" asp-for="StartDate"></label>
                    <input class="form-control filterable" asp-for="StartDate">
                </div>
                <div class="form-group">
                    <label class="control-label" asp-for="EndDate"></label>
                    <input class="form-control filterable" asp-for="EndDate">
                </div>

                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    @*</div>*@
</nav>

Web/Views/Shared/_BoxInput.cshtml
@{Layout = "~/Views/Shared/_Layout.cshtml"; }
<div class="box">
    <div class="box-header">
        <h3 class="box-title">@ViewBag.BoxTitle</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        @RenderBody()
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/Shared/_Header.cshtml
<header class="main-header">
    <a asp-controller="Home" asp-action="Index" class="logo">
        <span class="logo-mini"><b>T</b>MT</span>
        <span class="logo-lg"><b>Track</b> My Time</span>
    </a>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav"></ul>
        </div>
    </nav>
</header>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TrackMyTime</title>
    <base href="~/" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        @*<link rel="stylesheet" href="~/css/site.css" />*@
        <link href="~/lib/admin-lte/dist/css/AdminLTE.css" rel="stylesheet" />
        <link href="~/lib/admin-lte/dist/css/skins/skin-blue.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link href="~/lib/Ionicons/css/ionicons.css" rel="stylesheet" />
        <link href="~/lib/kendo-ui/styles/kendo.common-bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/kendo-ui/styles/kendo.bootstrap.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link href="~/lib/admin-lte/dist/css/AdminLTE.min.css" rel="stylesheet" />
        <link href="~/lib/admin-lte/dist/css/skins/skin-blue.min.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/lib/Ionicons/css/ionicons.min.css" rel="stylesheet" />
        @*<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />*@
        <link href="~/lib/kendo-ui/styles/kendo.common-bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/kendo-ui/styles/kendo.bootstrap.min.css" rel="stylesheet" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/admin-lte/dist/js/adminlte.js"></script>
        @*<script src="~/js/site.js" asp-append-version="true"></script>*@
        <script src="~/lib/kendo-ui/js/kendo.all.min.js"></script>
        <script src="~/lib/kendo-ui/js/kendo.aspnetmvc.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/lib/admin-lte/dist/js/adminlte.min.js"></script>
        @*<script src="~/js/site.min.js" asp-append-version="true"></script>*@
        <script src="~/lib/kendo-ui/js/kendo.all.min.js"></script>
        <script src="~/lib/kendo-ui/js/kendo.aspnetmvc.min.js"></script>
    </environment>
    <script src="http://kendo.cdn.telerik.com/2017.3.1026/js/jszip.min.js"></script>
</head>
<body class="hold-transition skin-blue fixed">
    <div class="wrapper">
        @Html.Partial("_Header")
        @Html.Partial("_Sidebar")
        <div class="content-wrapper">
            <div class="container">
                <section class="content-header">
                    <h1>
                        @ViewBag.Title
                    </h1>
                    <small>@ViewBag.Description</small>
                </section>
                <section class="content">
                    @RenderBody()
                </section>
            </div>
        </div>
        <footer class="main-footer fixed">
            <strong>Copyright &copy; 2017</strong>
        </footer>
    </div>
    <script src="~/dist/vendor.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Web/Views/Shared/_Sidebar.cshtml
<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            <li><a asp-controller="Activity" asp-action="Index"><i class="fa fa-clock-o"></i> <span>Activities</span></a></li>
            <li><a asp-controller="Report" asp-action="Index"><i class="fa fa-file-excel-o"></i> <span>Reports</span></a></li>
            <li class="header">MANAGE</li>
            <li><a asp-controller="Project" asp-action="Index"><i class="fa fa-folder-o"></i> <span>Projects</span></a></li>
            <li><a asp-controller="Client" asp-action="Index"><i class="fa fa-user-circle-o"></i> <span>Clients</span></a></li>
        </ul>
    </section>
</aside>